function generateLetterPdf_(p,actor){requireAdmin_(actor);const x=p.letter||{},c=p.config||{},name=safeFileName_((x.jenis||'Surat')+'-'+(x.nama||'Warga')+'-'+Date.now()+'.pdf');return {ok:true,file:createPdfDoc_(name,'Surat',function(body){appendHeader_(body,c);body.appendParagraph(String(x.jenis||'SURAT KETERANGAN').toUpperCase()).setHeading(DocumentApp.ParagraphHeading.HEADING2).setAlignment(DocumentApp.HorizontalAlignment.CENTER);if(x.nomor)body.appendParagraph('Nomor: '+x.nomor).setAlignment(DocumentApp.HorizontalAlignment.CENTER);body.appendParagraph('');appendIdentity_(body,x);if(x.perihal)body.appendParagraph('Perihal: '+x.perihal).setBold(true);body.appendParagraph(String(x.isi||x.keperluan||'')).setLineSpacing(1.35);appendClosing_(body,c,x.nama||'Pemohon');})}}
function generateLoanPdf_(p,actor){
  requireAdmin_(actor);const x=p.loan||{},c=p.config||{},items=loanItems_(x),name=safeFileName_('Pernyataan-Peminjaman-'+(x.Nama||'Warga')+'-'+Date.now()+'.pdf');
  return {ok:true,file:createPdfDoc_(name,'Surat',function(body){
    appendHeader_(body,c);
    body.appendParagraph('SURAT PERNYATAAN PEMINJAMAN ASET').setBold(true).setFontSize(13).setAlignment(DocumentApp.HorizontalAlignment.CENTER);
    body.appendParagraph('Nomor: '+(x.NomorSurat||x.ID||'-')).setFontSize(9).setAlignment(DocumentApp.HorizontalAlignment.CENTER);
    body.appendParagraph('Saya yang bertanda tangan di bawah ini:');
    const ident=body.appendTable();[['Nama Peminjam',x.Nama],['Alamat',x.Alamat],['No. HP / WhatsApp',x.NoHP],['Periode',(x.TanggalMulai||'')+' s.d. '+(x.TanggalSelesai||'')+(x.LamaHari?' ('+x.LamaHari+' hari)':'')],['Keperluan',x.Keperluan]].forEach(r=>{const row=ident.appendTableRow();row.appendTableCell(r[0]);row.appendTableCell(': '+(r[1]||'-'))});
    body.appendParagraph('Dengan ini menyatakan meminjam aset milik '+(c.RT_NAME||'RT 01 RW 04')+' dengan rincian sebagai berikut:').setLineSpacing(1.25);
    const t=body.appendTable();const h=t.appendTableRow();['No','Nama Aset','Qty','Tarif/Hari','Biaya Sewa','Deposit'].forEach(v=>h.appendTableCell(v));items.forEach((it,i)=>{const row=t.appendTableRow();row.appendTableCell(String(i+1));row.appendTableCell(String(it.AssetNama||'-'));row.appendTableCell(String(it.Jumlah||0));row.appendTableCell(rupiah_(it.TarifHarian||0));row.appendTableCell(rupiah_(it.BiayaSewa||0));row.appendTableCell(rupiah_(it.DepositTotal!=null?it.DepositTotal:(Number(it.Deposit||0)*Number(it.Jumlah||0))))});
    body.appendParagraph('Total biaya sewa: '+rupiah_(x.BiayaSewa||0)+'    |    Total deposit: '+rupiah_(x.Deposit||0)+'    |    Total estimasi: '+rupiah_(x.TotalTagihan||0)).setBold(true).setFontSize(9).setAlignment(DocumentApp.HorizontalAlignment.RIGHT);
    body.appendParagraph('Saya bersedia dan bertanggung jawab untuk:').setBold(true);const list=['Menjaga seluruh aset dengan baik selama masa peminjaman.','Menggunakan aset sesuai fungsi dan keperluan yang disampaikan.','Tidak memindahtangankan sebagian atau seluruh aset tanpa persetujuan pengurus.','Mengembalikan seluruh aset tepat waktu dalam kondisi baik, lengkap, dan sesuai jumlah yang dipinjam.','Bertanggung jawab atas kerusakan atau kehilangan setiap aset sesuai ketentuan Pengurus RT.'];list.forEach((v,i)=>body.appendListItem(v).setGlyphType(DocumentApp.GlyphType.NUMBER));
    body.appendParagraph('Pernyataan ini dibuat dengan sadar dan tanpa paksaan untuk dipatuhi sebagaimana mestinya.').setLineSpacing(1.35);
    body.appendParagraph((c.LETTER_CITY||'Pegandekan')+', '+Utilities.formatDate(new Date(),Session.getScriptTimeZone()||'Asia/Jakarta','dd MMMM yyyy')).setFontSize(9).setAlignment(DocumentApp.HorizontalAlignment.RIGHT);
    appendThreeSignsWithImages_(body,[{title:'Peminjam Aset',name:x.Nama||'Peminjam',fileId:x.TandaTanganPeminjamFileId,url:x.TandaTanganPeminjamUrl},{title:'Bendahara',name:c.BENDAHARA||'Bendahara',fileId:c.SIGN_BENDAHARA_FILE_ID,url:c.SIGN_BENDAHARA_URL},{title:'Ketua '+(c.RT_NAME||'RT 01 RW 04'),name:c.KETUA_RT||'Ketua RT',fileId:c.SIGN_KETUA_FILE_ID,url:c.SIGN_KETUA_URL}]);
    if(c.LETTER_FOOTER)body.appendParagraph(String(c.LETTER_FOOTER)).setFontSize(7).setForegroundColor('#777777').setAlignment(DocumentApp.HorizontalAlignment.CENTER);
  })}
}
function generateReportPdf_(p,actor){requireAdmin_(actor);const r=p.report||{},c=p.config||{},type=String(r.type||'FINANCE').toUpperCase(),title=type==='FINANCE'?(c.REPORT_FINANCE_TITLE||'LAPORAN KEUANGAN BULANAN'):(c.REPORT_INVENTORY_TITLE||'LAPORAN INVENTARIS BULANAN'),name=safeFileName_(title+'-'+(r.period||'')+'.pdf');return {ok:true,file:createPdfDoc_(name,'Laporan',function(body){appendHeader_(body,c);body.appendParagraph(title).setHeading(DocumentApp.ParagraphHeading.HEADING2).setAlignment(DocumentApp.HorizontalAlignment.CENTER);body.appendParagraph('Periode: '+(r.period||'-')).setAlignment(DocumentApp.HorizontalAlignment.CENTER);const s=r.summary||{};body.appendParagraph(Object.keys(s).map(k=>k+': '+formatReportValue_(s[k])).join(' | ')).setBold(true);const rows=r.rows||[];if(rows.length){const keys=Object.keys(rows[0]).filter(k=>!['updatedAt','createdAt','updatedBy'].includes(k)).slice(0,8),t=body.appendTable();const h=t.appendTableRow();keys.forEach(k=>h.appendTableCell(k));rows.forEach(x=>{const tr=t.appendTableRow();keys.forEach(k=>tr.appendTableCell(String(x[k]??'')))})}appendTwoSigns_(body,c.BENDAHARA||'Bendahara',c.KETUA_RT||'Ketua RT');})}}
function createPdfDoc_(fileName,category,build){const doc=DocumentApp.create(fileName.replace(/\.pdf$/i,'')),body=doc.getBody();build(body);doc.saveAndClose();const src=DriveApp.getFileById(doc.getId()),blob=src.getAs(MimeType.PDF).setName(fileName),root=ensureRootFolder_(),cat=ensureChildFolder_(root,category),d=new Date(),year=ensureChildFolder_(cat,String(d.getFullYear())),month=ensureChildFolder_(year,String(d.getMonth()+1).padStart(2,'0')),pdf=month.createFile(blob);src.setTrashed(true);return fileInfo_(pdf,false)}
function appendHeader_(body,c){
  const t=body.appendTable(),row=t.appendTableRow(),left=row.appendTableCell(),mid=row.appendTableCell(),right=row.appendTableCell();t.setBorderWidth(0);
  const logo=imageBlob_(c.LETTER_LOGO_FILE_ID,c.LETTER_LOGO_URL);if(logo){try{left.appendImage(logo).setWidth(58).setHeight(58)}catch(e){}}
  mid.appendParagraph(c.LETTER_ORG_NAME||'PENGURUS RT 01 RW 04').setBold(true).setFontSize(14).setAlignment(DocumentApp.HorizontalAlignment.CENTER);
  mid.appendParagraph(c.LETTER_ORG_SUBTITLE||'DUSUN II DESA PEGANDEKAN').setBold(true).setFontSize(10).setAlignment(DocumentApp.HorizontalAlignment.CENTER);
  mid.appendParagraph(c.LETTER_ADDRESS||'Kecamatan Kemangkon, Kabupaten Purbalingga').setFontSize(8).setAlignment(DocumentApp.HorizontalAlignment.CENTER);
  if(c.PHONE)mid.appendParagraph('Kontak: '+c.PHONE).setFontSize(8).setAlignment(DocumentApp.HorizontalAlignment.CENTER);right.appendParagraph('');body.appendHorizontalRule();body.appendHorizontalRule();
}
function loanItems_(x){if(Array.isArray(x.Items)&&x.Items.length)return x.Items;try{const a=JSON.parse(x.ItemsJson||'[]');if(Array.isArray(a)&&a.length)return a}catch(e){}return x.AssetNama?[{AssetID:x.AssetID||'',AssetNama:x.AssetNama,Jumlah:Number(x.Jumlah||1),TarifHarian:Number(x.TarifHarian||0),Deposit:Number(x.DepositPerUnit||0),BiayaSewa:Number(x.BiayaSewa||0),DepositTotal:Number(x.Deposit||0)}]:[]}
function rupiah_(v){return 'Rp '+Number(v||0).toLocaleString('id-ID')}
function driveIdFromUrl_(url){const s=String(url||''),m=s.match(/\/d\/([a-zA-Z0-9_-]{15,})/)||s.match(/[?&]id=([a-zA-Z0-9_-]{15,})/);return m?m[1]:''}
function imageBlob_(fileId,url){const id=fileId||driveIdFromUrl_(url);if(id){try{return DriveApp.getFileById(id).getBlob()}catch(e){}}if(url){try{const r=UrlFetchApp.fetch(url,{muteHttpExceptions:true,followRedirects:true});if(r.getResponseCode()<400)return r.getBlob()}catch(e){}}return null}
function appendThreeSignsWithImages_(body,sigs){const t=body.appendTable(),r1=t.appendTableRow(),r2=t.appendTableRow(),r3=t.appendTableRow();t.setBorderWidth(0);sigs.forEach(s=>{r1.appendTableCell(String(s.title||''));const cell=r2.appendTableCell();const blob=imageBlob_(s.fileId,s.url);if(blob){try{cell.appendImage(blob).setWidth(95).setHeight(52)}catch(e){cell.appendParagraph('\n\n')}}else cell.appendParagraph('\n\n');r3.appendTableCell(String(s.name||''))})}

function appendIdentity_(body,x){const rows=[['Nama Lengkap',x.nama||x.Nama],['Tempat/Tgl Lahir',x.tempatTanggalLahir||x.TempatTanggalLahir],['Jenis Kelamin',x.jenisKelamin||x.JenisKelamin],['Agama',x.agama||x.Agama],['NIK',x.nik||x.NIK],['Alamat',x.alamat||x.Alamat],['Keperluan',x.keperluan||x.Keperluan]].filter(r=>r[1]);if(!rows.length)return;const t=body.appendTable();rows.forEach(r=>{const tr=t.appendTableRow();tr.appendTableCell(r[0]);tr.appendTableCell(': '+r[1])})}
function appendClosing_(body,c,nama){body.appendParagraph('Demikian surat ini dibuat untuk dipergunakan sebagaimana mestinya.').setLineSpacing(1.35);appendTwoSigns_(body,nama||'Pemohon',c.KETUA_RT||'Ketua RT')}
function appendTwoSigns_(body,a,b){const t=body.appendTable([['Pemohon / Pihak Terkait','Ketua RT'],['\n\n\n'+a,'\n\n\n'+b]]);t.setBorderWidth(0)}
function appendThreeSigns_(body,a,b,c){const t=body.appendTable([['Peminjam Aset','Bendahara','Ketua RT'],['\n\n\n'+a,'\n\n\n'+b,'\n\n\n'+c]]);t.setBorderWidth(0)}
function formatReportValue_(v){if(typeof v==='number')return 'Rp '+v.toLocaleString('id-ID');return String(v??'')}
